import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
import React from 'react';
import {Geist, Geist_Mono} from "next/font/google";
import type {Metadata} from "next";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function LocaleLayout({
                                               children,
                                               params
                                           }: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    const {locale} = await params; // "vi" hoặc "en"
    console.log(locale);

    let messagesAll;
    try {
        messagesAll = (await import((`../../messages/${locale}/common.json`))).default; // import 1 file duy nhất
    } catch (error) {
        notFound();
    }

    // Trích xuất messages theo locale từ JSON
    const messages = messagesAll;
    if (!messages) notFound();

    return (
        <div className={'w-full h-full'}>
            <NextIntlClientProvider locale={locale} messages={messages}>
                {children}
            </NextIntlClientProvider>
        </div>
    );
}
